version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: beauty_supply_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: